model:
  model_id: cnn3d
  resnet_config:
    ch_0: 32
    ch_max: 128
    blocks_per_stage: [2,2,2,2,2]
  transformer_config:
    n_layers: 3
    n_heads: 6
    d_model: 384
  n_buttons: 11
  n_mouse_axes: 2

train:
  trainer_id: idm_trainer
  data_id: cod_data
  target_batch_size: 128
  batch_size: 16
  epochs: 200000
  opt: AdamW
  opt_kwargs:
    lr: 1.0e-4
    weight_decay: 0.01
    eps: 1.0e-15
    betas: [0.9, 0.999]
  scheduler: null
  checkpoint_dir: "checkpoints/v0"
  resume_ckpt: null
  sample_interval: 1000
  save_interval: 1000

wandb:
  name: shahbuland
  project: owl_idms
  run_name: v0
