optim:
  epochs: 10
  accumulation_steps: 1
  grad_max_norm: 1.0
  iterations_per_epoch: 500
  optimizer:
    _target_: owl_idms.optim.muon
    _partial_: true
    lr : 7.5e-4
    momentum: 0.95
    adamw_lr :  7.5e-5
    adamw_eps: 1.0e-15
    adamw_betas: [0.9, 0.999]

logging:
  save_epoch_frequency: 1
  log_step_frequency: 1
  log_vis_frequency: 100
  eval_every_n_epochs: 1
  load_path: null
  # load_path: /home/sami/owl_idms/outputs/2025-05-26/03-50-06/epoch_4.pt

hardware:
  device: cuda
  world_size: 1
  local_rank: null # set at runtime
  global_rank: null # set at runtime

loss:
  _target_: owl_idms.modules.mouse_loss


train_dataloader:
  _target_: owl_idms.data.get_cod_loader
  split: train
  batch_size: 256
  num_workers:  16
val_dataloader:
  _target_: owl_idms.data.get_cod_loader
  split: val
  batch_size: 64
  num_workers: 6

modules:
  action_predictor:
    _target_: owl_idms.modules.st_idm
