hydra:
  run:
    dir: ${idm_pretrain_id:${trainer}}

optim:
  epochs: 10
  batch_size: 128
  accumulation_steps: 1
  grad_max_norm: 1.0
  optimizer:
    _target_: owl_idms.optim.muon
    _partial_: True
    lr: 0.0003
  weight_decay: [0.01, 0.001]

logging:
  save_epoch_frequency: 1
  log_step_frequency: 100
  save_path: ./checkpoints

hardware:
  device: cuda
  world_size: 1
  local_rank: 0
  global_rank: 0

loss:
  _target_: owl_idms.modules.idm_loss
  mouse_weight: 0.3
  eps: 1e-6
  full: True
  reduction: mean

train_dataloader:
  _target_: owl_idms.data.dummy_dataloader
  split: train

val_dataloader:
  _target_: owl_idms.data.dummy_dataloader
  split: val

modules:
  vae_encoder:
    _target_: owl_idms.modules.vae_debug
  action_predictor:
    _target_: owl_idms.modules.idm_vpt_pico
