defaults:
  - hardware
  - logger/checkpointing
  - logger/wandb
  - logger/metrics
  - _self_


hydra:
  run:
    dir: ${idm_pretrain_id}


trainer:
  module:
    vae_encoder: ...
    vae_decoder: ...
    optical_flow_predictor: ...
    depth_map_predictor: ...
    action_predictor: ...
  data:
    train: ...
    val: ...
  optim:
    weight_decay: ...    
  loss: ...
