model:
    model_id: st_transformer
    st_transformer_config:
      depth: 4
      d_model: 384
      num_heads: 6
      token_drop: 0.1
      n_keys: 12
      img_size: [128, 128]
      patch: 16
      frames: 32
    n_buttons: 11
    n_mouse_axes: 2
  
  train:
    trainer_id: idm_trainer
    data_id: cod_data
    target_batch_size: 560
    batch_size: 112
    epochs: 200
    opt: Muon
    opt_kwargs:
      lr: 6.0e-5
      momentum: 0.95
      adamw_lr: 3.0e-4
      adamw_wd: 0.01
      adamw_eps: 1.0e-15
      adamw_betas: [0.9, 0.95]
      adamw_keys:
        [embed, mouse_head_mu, mouse_head_logvar, btn_head]
    loss_weights: null
    scheduler: null
    scheduler_kwargs: null
    checkpoint_dir: "checkpoints/v0"
    resume_ckpt: null
    sample_interval: 1000
    save_interval: 300
  
  wandb:
    name: samibg
    project: owl_idms
    run_name: v0-${model.model_id}-larger
  